common: &COMMON_PROPERTIES
  command_topic_name: &command_topic_name key_teleop

key_teleop_node:
  <<: *COMMON_PROPERTIES
  out_topic: *command_topic_name
  rate: 8

motor_driver_node:
  <<: *COMMON_PROPERTIES
  in_topic: *command_topic_name
  duty_cycle_step: 20
